name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config $BUILD_TYPE
